server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5430/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration-time: 600000      # 10 분
    refresh-expiration-time: 604800000  # 7 일

#   필요한 경우 Redis·MongoDB·AWS 설정은 주석 해제 후 사용
# spring:
#   data:
#     redis:
#       host: ${REDIS_HOST}
#       port: 6379
#   cloud:
#     aws:
#       ...

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /docs/swagger
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
